apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-watcher-sa
  namespace: default
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-watcher-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-watcher-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: pod-watcher-sa
    namespace: default
roleRef:
  kind: Role
  name: pod-watcher-role
  apiGroup: rbac.authorization.k8s.io